# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: valgrind
      run: sudo apt-get install -y gcc valgrind cmake

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: $GITHUB_WORKSPACE/scripts/build_coverage.sh
  
  windows-build:
    # The type of runner
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.6.x'

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: cmd
        run: $GITHUB_WORKSPACE\scripts\build_project.cmd
